---
galaxy_info:
  author: Astra Scholarship Team
  description: Skeleton role for PC/SC token dependencies on Astra Linux.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: GenericLinux
      versions:
        - all
dependencies: []
